version: '3'
services:
  react-ui:
    build:
      context: ./app
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./app:/app
       - /app/node_modules
    command: yarn start
  react-storybook:
    build:
      context: ./app
    ports:
      - "6006:6006"
    container_name: react-storybook
    stdin_open: true
    volumes:
       - ./app:/app
       - /app/node_modules
    command: yarn storybook
